# Simple mapping configuraton used to auto generate exported modules

ramda:
  module_name: r
rxjs:
  module_name: rx
  namespaces:
    - testing
    - operators
    - websocket
    - ajax
chance:
  module_name: chance
mathjs:
  module_name: math
yaml:
  module_name: yaml
esm:
  module_name: esm
json-schema-faker:
  module_name: jsf
