# Simple mapping configuraton used to auto generate export
#

ramda:
  module_name: r
rxjs:
    rx



-
  filename: r
  pkg_name: ramda
-
  filename: rxjs
  pkg_name: rx
-
  filename: chance
  pkg_name: chance
-
  filename: math
  pkg_name: mathjs
-
  filename: yaml
  pkg_name: yaml
-
  filename: esm
  pkg_name: esm
-
  filename: jsf
  pkg_name: json-schema-faker
